# This is a basic workflow to help you get started with Actions

name: Github_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      OPB: ${{ steps.Run.outputs.test }    
    defaults:
      run:
        shell : bash
        working-directory: ./scripts    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run
        run: ./build.sh >> "$GITHUB_OUTPUT"
        continue-on-error: true
      - name: Check
        if: steps.Run.outcome  != 'success'
        run: exit 1

  test:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell : bash
        working-directory: ./scripts    
    steps:
      - env:
          OPT: ${{needs.build.outputs.OPB}}
      - name: Checkout to runner
        uses: actions/checkout@v3

      - name: Run script
        run: ./test.sh "OPT"
