# This is a basic workflow to help you get started with Actions

name: Github_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell : bash
        working-directory: ./scripts    
    steps:
      - name: Checkout to runner
        uses: actions/checkout@v3

      - name: Run
        run: 'bash build.sh'
        continue-on-error: true

      - name: Run2
        run: 'bash bui.sh'
        continue-on-error: true

      - name: Check
        if: steps.Run.outcome  != 'success' || steps.Run2.outcome  != 'success'
        run: exit 1

  test:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell : bash
        working-directory: ./scripts    
    steps:
      - name: Checkout to runner
        uses: actions/checkout@v3

      - name: Run script
        run: 'bash test.sh'
