# This is a basic workflow to help you get started with Actions

name: Github_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      op: ${{ steps.runbuild.outputs.out }}    
    defaults:
      run:
        shell : bash
        working-directory: ./scripts    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Build
        id: runbuild  
        continue-on-error: true        
        run: >
            bo=$(./build.sh);
            echo "out=$bo" >> "$GITHUB_OUTPUT"
        
      - name: Check
        if: steps.runbuild.outcome  != 'success'
        run: exit 1

  test:
    if: success()
    needs: build
    runs-on: ubuntu-latest
    env:
        OPT: ${{ needs.build.outputs.op }}
    defaults:
      run:
        shell: bash
        working-directory: ./scripts    
    steps:
      - name: Checkout to runner
        uses: actions/checkout@v3

      - name: Run Initialtest
        run: echo "FOO=35" >> "$GITHUB_ENV"    
      - name: Run Secondtest
        run: |
            ./test.sh "$OPT"
            ./test.sh "$FOO"
      - name: Run ThirdTest 
        run: >
            bo=$(./build.sh);
            echo "final=$bo" >> "$GITHUB_ENV"
      - name: Run FinalTest 
        run: echo "$final"
            
