# This is a basic workflow to help you get started with Actions

name: Github_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      OPB: ${{ steps.Run.outputs.test }}    
    defaults:
      run:
        shell : bash
        working-directory: ./scripts    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run
        uses: 'selfagency/capture-output@v1'
        with:
          cmd: cd scripts; ./build.sh
          hide-warnings: true
      - name: Check
        if: steps.Run.outcome != 'success'
        run: exit 1

  test:
    if: ${{ always() }}
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell : bash
        working-directory: ./scripts    
    steps:
      - name: Checkout to runner
        uses: actions/checkout@v3
      - env:
          OPT: ${{needs.build.outputs.OPB}}
        run: ./test.sh "OPT"
